---
deployment:
  tasks:
    - export DEPLOYPATH=/home/alghool/
    - /bin/cp -r * $DEPLOYPATH/projects_core/movies/
    - /bin/cp -r ./public/favicon.ico $DEPLOYPATH/public_html/movies/
    - /bin/cp -r ./public/mix-manifest.json $DEPLOYPATH/public_html/movies/
    - /bin/cp -r ./public/robots.txt $DEPLOYPATH/public_html/movies/
    - /bin/cp ./public/js/*.js $DEPLOYPATH/public_html/movies/js
    - /bin/cp ./public/css/*.css $DEPLOYPATH/public_html/movies/css
    - /bin/cp ./public/img/*.png $DEPLOYPATH/public_html/movies/img